apiVersion: v1
kind: ConfigMap
metadata:
  name: loteria-console-config
  namespace: ns-loteria
data:
  DOTNET_ENVIRONMENT: "Production"
  OpenTelemetry__Jaeger__Endpoint: "http://jaeger-collector.observability.svc.cluster.local:4318/v1/traces"
  OpenTelemetry__Jaeger__Protocol: "HttpProtobuf"
  OpenTelemetry__Jaeger__ServiceName: "loteria-console"
  OpenTelemetry__Jaeger__ServiceVersion: "1.0.0"
  LoteriaApi__BaseUrl: "https://servicebus3.caixa.gov.br/portaldeloterias/api"
  LoteriaApi__Throttle: "1100"
  LoteriaApi__TimeoutSeconds: "60"
  App__ExecutionMode: "Daily"