name: loteria

services:
  mssql:
    hostname: "sql-server2022"
    container_name: "sql-server2022"
    build:
      context: ../backend/scripts
      dockerfile: Dockerfile
    image: "sql-server2022"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: ${SA_PASSWORD}
      TZ: America/Cuiaba
    volumes:
      - mssql:/var/opt/mssql
      - ../backend/scripts:/scripts:ro
    ports:
      - '1433:1433'
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $$SA_PASSWORD -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks:
      - loteria_network

  app-loteria-console:
    container_name: "app-loteria-console"
    hostname: "app-loteria-console"
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      Data__AppConnection: "Server=mssql;Database=Loteria;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      DOTNET_ENVIRONMENT: "Development"
    image: image-loteria-console
    networks:
      - loteria_network
    depends_on:
      mssql:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:1.58
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - loteria_network

volumes:
  mssql:

networks:
  loteria_network:
    driver: bridge